### ISSUE TITLE
there a error in last line with = sign im using python2.7

### ISSUE THREAD

**Issue by prateekrajgautam** [scotartt/clean_bib#1]
bibtex_str = None
if bib_database:
    writer = BibTexWriter()
    writer.order_entries_by = ('author', 'year', 'type')
    bibtex_str = bibtexparser.dumps(bib_database, writer)
   # print(str(bibtex_str))
    with open(output_b, "w") as text_file:
        print(bibtex_str, file=text_file)

i am not expert in python but if i comment this line script works and says written ## no of entries new file is created but it is empty

**Comment by scotartt** [comment]
yes, hello as I said in the readme, this only works with python 3.x
