### ISSUE TITLE
Converting to unicode fixes ampersands but breaks Overleaf

### ISSUE THREAD

**Issue by erikr** [scotartt/clean_bib#2]
Converting to unicode replaces instances of `{\&}` with `&` which is intended behavior, but it introduces errors in Overleaf.

Commenting out line 22 fixes this:

```
# record = convert_to_unicode(record)
```

I wonder if there is a way to call `convert_to_unicode` but spare ampersands.

**Comment by scotartt** [comment]
Hi, I don't know what "Overleaf" is. I just normally use unicode (UTF-8) everywhere anyway, and would only use tools that support it. The convert to unicode function is from the bibtex library.
