### ISSUE TITLE
Consistency checks

### ISSUE THREAD

**Issue by julianthome** [scotartt/clean_bib#3]
Thanks for this great tool 👍. Are you also planning to integrate consistency checks. As an example, let's say you have a paper where you put "Proceedings of ICSE'09" in the field "booktitle". Another entry says "Proceedings of International Conference on Software Engineering (ICSE) 2019". There is, of course, no general solution for this problem, but a couple of simple heuristics that could find these inconsistencies would already help a lot.

**Comment by scotartt** [comment]
I suspect that a general solution to this issue would be too large for the small amount of code this is. It would probably throw up too many false positives where you have a lot of journals and books with similar but not exactly the same titles.

**Comment by julianthome** [comment]
Hi @scotartt,
yes, I see what you mean. I was just thinking it would be great if the tool could provide some clues where potential inconsistencies may lie. But I get your point.
Thanks again @scotartt and kind regards, 
  Julian
